apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: django
  labels:
     krules.airspot.dev/type: django-admin
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      labels:
        krules.airspot.dev/type: django-admin
    spec:
      containers:
      - name: django
        image: lorenzocampo/django-iot-demo:pre14
---

apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
 name: django
spec:
 subject:
   apiVersion: apps/v1
   kind: Deployment
   selector:
     matchLabels:
       serving.knative.dev/service: django
 sink:
   ref:
     apiVersion: eventing.knative.dev/v1
     kind: Broker
     name: default

