apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: default-to-class-a-trigger
spec:
  broker: default
  filter:
    attributes:
      deviceclass: class-a
  subscriber:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: class-a
