apiVersion: krules.airspot.dev/v1alpha1
kind: ConfigurationProvider
metadata:
  name: config-krules-django-restapi
spec:
  key: django.restapi
  appliesTo:
    configs.krules.airspot.dev/django-restapi-consumer: inject
  data:
    url: $RESTAPI_URL
    api_key: $RESTAPI_TOKEN
  container:
    envFrom:
      - secretRef:
          name: restapi-auth
