apiVersion: krules.airspot.dev/v1alpha1
kind: ConfigurationProvider
metadata:
  name: config-krules-django-restapi
spec:
  key: django.restapi
  appliesTo:
    configs.krules.airspot.dev/django-restapi-consumer: inject
  data:
    url: "http://django-device-admin.iot-demo.gke1.airspot.dev"
    api_key: $RESTAPI_TOKEN
  container:
    envFrom:
      - secretRef:
          name: restapi-auth
    env:
      - name: TEST_VAR
        value: "hi there, again and again and again and again and again and again"
